### ISSUE TITLE
The project is stuck in prerelease since 2016

### ISSUE THREAD

**Issue by ruimaciel** [joeaudette/GeoJSON.NetCore#2]
Currently, a search in nuget for GeoJSON still returns GeoJSON.NetCore as one of the first search hits.  However, the project site states that the only available version is a prerelease version, which has been published back in 2016.

It would be nice if a stable version was released, preferably one that targeted the .Net Core 2.1 framework (the LTS version) and also played well with EntityFramework.

**Comment by joeaudette** [comment]
I ported this to .NET Core back in 2016 thinking I needed it for a project but never ended up using it for any project. I don't have an interest in maintaining this. If you want an updated version I suggest fork it and update it and publish your own nuget.

**Comment by ruimaciel** [comment]
In that case could you please delist the package from nuget? Being listed conveys the idea that the project isn't dead and may actually be about to release a new version.

**Comment by joeaudette** [comment]
done
